"""This module contains the ids used in the components."""

UPLOAD_FILE = "upload-file"
UPLOAD_FEEDBACK = "upload-feedback"
UPLOAD_FILE_STORE = "upload-file-store"
STORED_DATA_TABLE = "stored-data-table"
PROCESS_BUTTON = "process-button"
PROCESS_BUTTON_LOADING = "process-button-loading"
PROCESS_BUTTON_INFO = "process-button-info"
FOLDER_PATH_TEXT = "folder-path-text"
RESULT_DICT = "result-dict"
DOWNLOAD_BUTTON = "download-button"
DOWNLOAD_FILE = "download-file"
DOWNLOAD_STORE = "download-store"
